"""readme.py — write README.md from data/seta/manifest.json, results/*.json and cards/.

Every number in the README is copied verbatim from a JSON value: the manifest, a gauge's
results/<gauge>.json (its `exam` block), its results/<gauge>.calib.json, results/canary.json or
results/ku2-hidden.json. Nothing is computed or rounded here except the "within noise" test, which
compares two CI intervals and only decides where a dagger goes. No set-A item text is read or
printed, and exam.jsonl is never opened. The harness reads JSON and never imports an engine.

The CI level is printed as digits only when a JSON value carries it (`ci_level` in the exam block
or the calib file); otherwise it is written in words, so no digit sequence lacks a JSON source.

Run from the repo root:  $PY -m nikasha.readme
"""
from __future__ import annotations

import argparse
import json
import sys
from decimal import Decimal
from pathlib import Path

from nikasha import CARDS_DIR, LABELS, MANIFEST_PATH, RESULTS_DIR, ROOT, read_json

README_PATH = ROOT / "README.md"
CURVE_REL = "results/curve.png"

# Table rows, in this order when present; any other scored gauge follows, sorted by name.
ROW_ORDER = ["baseline-uniform", "baseline-majority", "gauge1-logit", "gauge3-probe", "jev"]
DISPLAY_NAME = {
    "baseline-uniform": "uniform",
    "baseline-majority": "majority-of-fit",
    "gauge1-logit": "gauge ① logit read",
    "gauge3-probe": "gauge ③ probe",
    "jev": "Jev (external, hosted, same 300 items)",
}
# Columns whose cell carries a CI (display key == metrics key); eligible for the "within noise" dagger.
CI_COLUMNS = ["accuracy", "ask_rate", "selective_accuracy", "auroc"]
# Columns whose cell shows two metrics as "raw → cal" (score.py's display string). Each half is
# bootstrapped with its own CI, so each half gets its own dagger: display key -> (raw key, cal key).
ARROW_COLUMNS = {"ece": ("ece_raw", "ece_cal")}
ARROW = " → "  # the separator score.py writes between the raw and cal halves
# Bootstrap/calibration parameters that must agree across every scored gauge. `ci_level` is optional:
# when no JSON carries it the level is printed in words (CI_LEVEL_WORDS), never as a hand-written digit.
SHARED_KEYS = ["n_boot", "seed", "ece_bins", "sa_target", "ci_level"]
OPTIONAL_SHARED_KEYS = {"ci_level"}
CI_LEVEL_WORDS = "ninety-five percent"

DASH = "—"
DAGGER = " †"
FOOTNOTE_TPL = "† within noise: {level} CIs overlap with another row."
UNIFORM_FOOTNOTE = ("A constant uniform predictor is calibrated by construction (confidence 1/3, accuracy ≈ 1/3), "
                    "so its ECE overlaps any well-calibrated gauge.")
LETTER_BIAS_SENTENCE = "averaging over three letter orders removes this bias."
# (promise, results file that fulfils it): a promise is dropped from the line once its result is scored.
PROMISED = [
    ("gauge ③ probe", "gauge3-probe.json"),
    ("Jev column", "jev.json"),
    ("embeddings gauge", None),
    ("set B", None),
    ("set C from the measured week", None),
]
FOOTER = ("Generated by nikasha/readme.py from results/*.json and data/seta/manifest.json — "
          "no number in this file is written by hand.")

# The contract paragraph is written in words so it carries no digit sequence of its own.
INTRO = (
    "One sealed exam, many decision gauges. A gauge is any program that, for one item, returns a "
    "probability vector over the fixed label list ({labels}): one entry per label, every entry "
    "between zero and one inclusive, and the entries summing to one within a tolerance of one part "
    "in a million. Each gauge is its own process and writes `results/<gauge>.json`; the harness "
    "(`calibrate.py`, `score.py`, `readme.py`) reads that JSON and never imports an engine."
)
# Used only when the manifest carries no label_rule; words, no digits.
FALLBACK_RULE = {
    "no-call": "the request cannot be served by the listed functions",
    "one-call": "the ground truth has exactly one call",
    "multi-call": "the ground truth has two or more calls",
}


# ----------------------------------------------------------------------------- helpers

def fmt(v) -> str:
    """Render a JSON value verbatim: numbers through json.dumps (the same text json.dump wrote),
    strings as they are, lists element-wise, None as a dash. A float that json.dumps writes in
    scientific notation (e.g. 3.0517578125e-05) is re-rendered positionally (0.000030517578125):
    the same value, every significant digit kept, nothing rounded — the form selftest derives
    from the JSON number itself."""
    if v is None:
        return DASH
    if isinstance(v, bool):
        return "true" if v else "false"
    if isinstance(v, (int, float)):
        s = json.dumps(v)
        if isinstance(v, float) and "e" in s:  # finite floats only: NaN/Infinity carry no 'e'
            s = format(Decimal(s), "f")
        return s
    if isinstance(v, str):
        return v
    if isinstance(v, (list, tuple)):
        return "[" + ", ".join(fmt(x) for x in v) + "]"
    return json.dumps(v, ensure_ascii=False)


def dig(obj, *keys):
    """Nested dict lookup; None when any key is missing."""
    for k in keys:
        if isinstance(obj, dict) and k in obj:
            obj = obj[k]
        else:
            return None
    return obj


def warn(msg: str) -> None:
    print(f"readme: warning: {msg}", file=sys.stderr)


def code(s) -> str:
    return f"`{s}`"


# ----------------------------------------------------------------------------- inputs

def load_json(path: Path):
    """read_json that never raises: a missing, truncated or otherwise unreadable file is a warning
    and None, so one damaged results file cannot block README generation (selftest reports it)."""
    try:
        return read_json(path)
    except (OSError, UnicodeDecodeError, ValueError) as e:  # json.JSONDecodeError is a ValueError
        warn(f"{path.name}: unreadable JSON ({type(e).__name__}); skipped")
        return None


def load_json_dict(path: Path) -> dict | None:
    """load_json, plus a warning and None when the top level is not a JSON object."""
    obj = load_json(path)
    if obj is not None and not isinstance(obj, dict):
        warn(f"{path.name}: top level is not a JSON object; skipped")
        return None
    return obj


def load_rows() -> list[dict]:
    """Every top-level results/<gauge>.json that has a `gauge` key and an `exam` block, with its
    .calib.json alongside (empty dict when absent). Ordered: ROW_ORDER first, then the rest by name."""
    found: dict[str, dict] = {}
    if RESULTS_DIR.exists():
        for path in sorted(RESULTS_DIR.glob("*.json")):
            if path.name.endswith(".calib.json") or not path.is_file():
                continue
            data = load_json(path)
            if not isinstance(data, dict) or "gauge" not in data:
                continue
            exam = data.get("exam")
            if not isinstance(exam, dict):
                continue
            stem = path.name[: -len(".json")]
            calib_path = RESULTS_DIR / f"{stem}.calib.json"
            calib = load_json_dict(calib_path) if calib_path.is_file() else None
            if calib is None:
                calib = {}
            found[stem] = {"id": stem, "gauge": data.get("gauge") or stem, "exam": exam, "calib": calib}
    rows = [found[g] for g in ROW_ORDER if g in found]
    rows += [found[g] for g in sorted(found) if g not in ROW_ORDER]
    return rows


def shared_exam_params(rows: list[dict]) -> dict:
    """n_boot / seed / ece_bins / sa_target, read from the exam block (calib file as fallback).
    They must agree across every scored gauge; a disagreement is an error, not a guess."""
    params: dict = {}
    for key in SHARED_KEYS:
        seen: dict[str, object] = {}
        for r in rows:
            v = r["exam"].get(key)
            if v is None:
                v = r["calib"].get(key)
            if v is not None:
                seen[r["id"]] = v
        distinct = {json.dumps(v) for v in seen.values()}
        if len(distinct) > 1:
            raise SystemExit(f"readme: `{key}` differs across scored gauges: {seen}")
        params[key] = next(iter(seen.values())) if seen else None
        if params[key] is None and key not in OPTIONAL_SHARED_KEYS:
            warn(f"`{key}` not found in any exam block or calib file; printing a dash")
    return params


def ci_level_text(shared: dict) -> str:
    """The CI level as printed: the JSON value followed by '%' when one exists, else in words."""
    v = shared.get("ci_level")
    return f"{fmt(v)}%" if v is not None else CI_LEVEL_WORDS


def first_license_line(card: Path) -> str | None:
    for line in card.read_text(encoding="utf-8").splitlines():
        s = line.strip()
        if s.startswith("license:"):
            return s
    return None


# ----------------------------------------------------------------------------- within noise

def ci_of(row: dict, metric: str):
    ci = dig(row["exam"], "metrics", metric, "ci")
    if (isinstance(ci, (list, tuple)) and len(ci) == 2
            and all(isinstance(x, (int, float)) and not isinstance(x, bool) for x in ci)):
        return (ci[0], ci[1])
    return None


def overlaps(a, b) -> bool:
    return a[0] <= b[1] and b[0] <= a[1]


def within_noise(rows: list[dict], metric: str) -> list[bool]:
    """flags[i] is True when row i's CI on `metric` overlaps the CI of at least one other row."""
    cis = [ci_of(r, metric) for r in rows]
    flags = []
    for i, a in enumerate(cis):
        flags.append(a is not None and any(
            b is not None and j != i and overlaps(a, b) for j, b in enumerate(cis)))
    return flags


# ----------------------------------------------------------------------------- sections

def intro_section() -> list[str]:
    labels = ", ".join(code(l) for l in LABELS)
    return ["# nikasha", "", INTRO.format(labels=labels)]


def install_section() -> list[str]:
    return ["## Install", "",
            "```",
            "git clone https://github.com/anjansastry-hash/nikasha.git && cd nikasha",
            "python -m venv .venv && source .venv/bin/activate",
            "pip install -r requirements.txt",
            "```", "",
            "Use a full clone, not a shallow clone or a ZIP: selftest checks f and i read the git history. "
            "`make selftest` needs no model download; `make gauge1` needs the 12B weights at `$NIKASHA_ENGINE` "
            "or `~/mlx-models/gemma-4-12b-8bit-text`."]


def _items(n) -> str:
    return f"{fmt(n)} item" + ("" if n == 1 else "s")


def _counter_line(what: str, block) -> str:
    """'Dropped for <what>: N item(s) (file: n, ...) — <manifest reason>.'"""
    line = f"Dropped for {what}: {_items(dig(block, 'total'))}"
    by_file = dig(block, "by_file")
    if isinstance(by_file, dict) and by_file:
        line += " (" + ", ".join(f"{name}: {fmt(n)}" for name, n in sorted(by_file.items())) + ")"
    reason = dig(block, "reason")
    return line + (f" — {reason}." if reason else ".")


def dropped_lines(m: dict) -> list[str]:
    """Both drop counters from the manifest: category contradictions and missing ground truth."""
    lines = [_counter_line("a category contradiction", dig(m, "dropped"))]
    if isinstance(dig(m, "dropped", "no_ground_truth"), dict):
        lines.append(_counter_line("missing ground truth", dig(m, "dropped", "no_ground_truth")))
    return lines


def seta_section(m: dict) -> list[str]:
    out = ["## Set A", ""]
    out.append(f"{fmt(m.get('name'))}: built from {code(fmt(m.get('source')))} "
               f"(license {fmt(m.get('source_license'))}) at dataset revision {code(fmt(m.get('bfcl_revision')))}. "
               f"Three labels, in fixed order:")
    out.append("")
    rules = m.get("label_rule") if isinstance(m.get("label_rule"), dict) else {}
    for label in LABELS:
        rule = rules.get(label) or FALLBACK_RULE.get(label) or DASH
        out.append(f"- {code(label)} — {rule}")
    out.append("")
    out.append("| | total | " + " | ".join(LABELS) + " |")
    out.append("|---|---|" + "---|" * len(LABELS))
    for name, total_path, label_path in (
        ("set A", ("counts", "total"), ("counts", "by_label")),
        ("fit", ("counts", "fit", "total"), ("counts", "fit", "by_label")),
        ("exam", ("counts", "exam", "total"), ("counts", "exam", "by_label")),
    ):
        by_label = dig(m, *label_path) or {}
        cells = [name, fmt(dig(m, *total_path))] + [fmt(by_label.get(l)) for l in LABELS]
        out.append("| " + " | ".join(cells) + " |")
    out.append("")
    for line in dropped_lines(m):
        out.append(line + "  ")
    out.append(f"Sampling draws at least {fmt(m.get('min_per_source_file'))} items from every "
               f"non-empty source file, so live and non-live items both appear. "
               f"Seed {fmt(m.get('seed'))} for sampling and split.")
    if m.get("exam_reduced"):
        out.append("The exam split was reduced by the pre-registered timing rule.")
    canary_path = RESULTS_DIR / "canary.json"
    if canary_path.exists():
        c = load_json_dict(canary_path)
        if c is None:
            warn("canary.json present but unusable; canary line omitted")
        else:
            flagged = bool(c.get("flagged"))
            out.append("")
            out.append(
                f"Canary (KU3): verbatim completions {fmt(c.get('verbatim_rate'))}, "
                f"twins {fmt(c.get('twin_rate'))} — "
                + ("contamination-flagged" if flagged else "not flagged")
                + "; gauge ① is reported as a "
                + ("read" if flagged else "zero-shot read") + "."
            )
    return out


def cell(display: dict, key: str, dagger: bool) -> str:
    s = fmt(display.get(key))
    if dagger and s != DASH:
        s += DAGGER
    return s


def arrow_cell(display: dict, key: str, daggers: tuple[bool, bool]) -> str:
    """A "raw → cal" cell: the display string is split on its arrow (no number is touched) and the
    dagger is appended to each half whose metric is within noise. A string of any other shape is
    marked as a whole when either half is."""
    parts = fmt(display.get(key)).split(ARROW)
    if len(parts) != 2:
        return cell(display, key, any(daggers))
    return ARROW.join(p + DAGGER if d and p != DASH else p for p, d in zip(parts, daggers))


def results_table(rows: list[dict]) -> list[str]:
    """The results table, its within-noise footnote and the bootstrap line (needs at least one row)."""
    out: list[str] = []
    shared = shared_exam_params(rows)
    level = ci_level_text(shared)
    header = ["gauge", "n_exam", "accuracy [CI]", "ECE raw → cal",
              f"ask rate @ SA {fmt(shared['sa_target'])} [CI]",
              "selective accuracy achieved [CI]", "AUROC [CI]"]
    noise = {m: within_noise(rows, m) for m in CI_COLUMNS}
    noise.update({m: within_noise(rows, m) for pair in ARROW_COLUMNS.values() for m in pair})
    out.append("| " + " | ".join(header) + " |")
    out.append("|" + "---|" * len(header))
    for i, r in enumerate(rows):
        display = r["exam"].get("display")
        if not isinstance(display, dict):
            display = {}
            warn(f"{r['id']}: exam block has no display strings; cells print as dashes")
        cells = [
            DISPLAY_NAME.get(r["id"], r["gauge"]),
            fmt(r["exam"].get("n_exam")),
            cell(display, "accuracy", noise["accuracy"][i]),
            arrow_cell(display, "ece", tuple(noise[m][i] for m in ARROW_COLUMNS["ece"])),
            cell(display, "ask_rate", noise["ask_rate"][i]),
            cell(display, "selective_accuracy", noise["selective_accuracy"][i]),
            cell(display, "auroc", noise["auroc"][i]),
        ]
        out.append("| " + " | ".join(cells) + " |")
    gj = load_gauge_j()
    if gj is not None:
        out.append(gauge_j_table_row(gj))
    out.append("")
    if any(any(flags) for flags in noise.values()):
        out.append(FOOTNOTE_TPL.format(level=level))
        out.append("")
    if any(r["id"] == "baseline-uniform" for r in rows):
        out.append(UNIFORM_FOOTNOTE)
        out.append("")
    out.append(
        f"{level} percentile bootstrap CIs, {fmt(shared['n_boot'])} resamples, seed {fmt(shared['seed'])}; "
        f"ECE with {fmt(shared['ece_bins'])} equal-width bins; "
        f"selective-accuracy target {fmt(shared['sa_target'])}; thresholds fitted on the fit split only."
    )
    if gj is not None:
        out.append("")
        out.append(gauge_j_footnote(gj))
    for r in rows:
        bias = r["calib"].get("letter_bias_fit")
        if isinstance(bias, dict) and bias.get("display"):
            out.append("")
            out.append(
                f"Letter bias of {DISPLAY_NAME.get(r['id'], r['gauge'])} ({fmt(bias.get('split'))} split, rotation r0 "
                f"minus the mean over rotations, logits per label in label order): {fmt(bias['display'])}; "
                + LETTER_BIAS_SENTENCE
            )
    return out


def results_section(rows: list[dict]) -> list[str]:
    """Table (when any gauge is scored), then the curve image and the KU2 line, each conditioned
    only on its file existing."""
    out = ["## Results", ""]
    if rows:
        out += results_table(rows)
    else:
        out.append("No gauge has an exam block yet.")
    if (ROOT / CURVE_REL).exists():
        out.append("")
        out.append(f"![selective accuracy vs ask rate]({CURVE_REL})")
    ku2_path = RESULTS_DIR / "ku2-hidden.json"
    if ku2_path.exists():
        k = load_json_dict(ku2_path)
        if k is None:
            warn("ku2-hidden.json present but unusable; hidden-state line omitted")
        else:
            out.append("")
            out.append(
                f"Hidden-state check (KU2): last hidden state shape {fmt(k.get('hidden_shape'))}, "
                f"head reproduces logits within max-abs {fmt(k.get('max_abs_diff'))} — "
                + ("PASS" if k.get("pass") else "FAIL") + "."
            )
    return out


LIKE_ORDER = ["gauge1-logit", "gauge3-probe", "jev"]
GATE_KEYS = {"gate_ask_rate": "ask_rate", "gate_selective_accuracy": "selective_accuracy"}


def like_for_like_section() -> list[str]:
    """The 300-item like-for-like group (gauges ①, ③ and Jev on the same items, paired resamples), the
    unfitted-gate columns, and the Jev call summary — every number from results/like-for-like.json and
    results/jev.json."""
    path = RESULTS_DIR / "like-for-like.json"
    like = load_json_dict(path) if path.is_file() else None
    if not isinstance(like, dict) or not isinstance(like.get("exam"), dict):
        return []
    ex = like["exam"]
    level = f"{fmt(ex.get('ci_level'))}%" if ex.get("ci_level") is not None else CI_LEVEL_WORDS
    sa_targets = {json.dumps(dig(load_json_dict(RESULTS_DIR / f"{name}.calib.json") or {}, "sa_target"))
                  for name in LIKE_ORDER if (RESULTS_DIR / f"{name}.calib.json").is_file()}
    if len(sa_targets) != 1:
        raise SystemExit(f"readme: sa_target differs across the like-for-like calibrations: {sa_targets}")
    sa_target = json.loads(next(iter(sa_targets)))
    rows = []
    for name in LIKE_ORDER:
        r = (like.get("rows") or {}).get(name)
        if not isinstance(r, dict):
            continue
        m = dict(r.get("metrics") or {})
        gate = r.get("unfitted_gate") or {}
        for key, src in GATE_KEYS.items():
            m[key] = gate.get(src) if isinstance(gate.get(src), dict) else {"value": None, "ci": None}
        rows.append({"id": name, "gauge": name, "exam": {"metrics": m, "display": r.get("display") or {}},
                     "gate_display": gate.get("display") or {}})
    noise = {k: within_noise(rows, k) for k in CI_COLUMNS + list(GATE_KEYS) + ["ece_raw", "ece_cal"]}
    tau = None
    for name in LIKE_ORDER:
        tau = dig(like, "rows", name, "unfitted_gate", "tau") if tau is None else tau
    out = ["## Like-for-like: the same 300 exam items", "",
           f"Gauges ① and ③ (their fit-split T and thresholds) and Jev on the same {fmt(like.get('n'))} exam items "
           f"(the Jev subsample, {fmt(like.get('n_jev_failed'))} Jev failures removed), one bootstrap order, so the "
           f"rows' resamples are paired. The last two columns are the unfitted gate \"answer iff max p ≥ {fmt(tau)}\" "
           "on each gauge's own final probabilities — no threshold fitted, reported for this group only.", "",
           f"| gauge | n | accuracy [CI] | ECE raw → cal | ask rate @ SA {fmt(sa_target)} [CI] | "
           f"selective accuracy achieved [CI] | AUROC [CI] | unfitted gate: ask rate [CI] | unfitted gate: selective accuracy [CI] |",
           "|" + "---|" * 9]
    for i, r in enumerate(rows):
        d, gd = r["exam"]["display"], r["gate_display"]
        cells = [DISPLAY_NAME.get(r["id"], r["id"]), fmt(like.get("n")),
                 cell(d, "accuracy", noise["accuracy"][i]),
                 arrow_cell(d, "ece", (noise["ece_raw"][i], noise["ece_cal"][i])),
                 cell(d, "ask_rate", noise["ask_rate"][i]),
                 cell(d, "selective_accuracy", noise["selective_accuracy"][i]),
                 cell(d, "auroc", noise["auroc"][i]),
                 cell(gd, "ask_rate", noise["gate_ask_rate"][i]),
                 cell(gd, "selective_accuracy", noise["gate_selective_accuracy"][i])]
        out.append("| " + " | ".join(cells) + " |")
    out.append("")
    if any(any(f) for f in noise.values()):
        out += [FOOTNOTE_TPL.format(level=level), ""]
    jev = load_json_dict(RESULTS_DIR / "jev.json") if (RESULTS_DIR / "jev.json").is_file() else None
    if isinstance(jev, dict):
        calls = jev.get("calls") or {}
        conf = jev.get("confidence")
        conf_txt = {"probabilities": "every response carried per-option probabilities, taken as its probability vector",
                    "none": "no response carried a confidence: one-hot vectors, ask rate n/a (no confidence returned)",
                    "mixed": "some responses carried no probabilities (one-hot, counted in results/jev.json)"}.get(conf, "")
        out.append(
            f"Jev: {fmt(jev.get('n_success'))} of {fmt(dig(jev, 'subsample', 'n'))} subsample items answered, "
            f"{fmt(jev.get('n_failed'))} failed (listed in `results/jev.json`); {fmt(calls.get('total'))} calls including "
            f"{fmt(calls.get('retries'))} retries (cap {fmt(calls.get('cap'))}); {conf_txt}. Nothing is fitted for an "
            "exam-only subsample: T = 1 and no thresholds, so its ask rate at fitted thresholds is n/a. Raw responses: "
            "`results/jev-raw/`."
        )
    return out


def share_of_gap_section() -> list[str]:
    """Task E: one line from results/share-of-gap.json — the analogue of the per-category threshold rung."""
    path = RESULTS_DIR / "share-of-gap.json"
    doc = load_json_dict(path) if path.is_file() else None
    if not isinstance(doc, dict) or not isinstance(doc.get("exam"), dict):
        return []
    d, ex = doc.get("display") or {}, doc["exam"]
    level = f"{fmt(ex.get('ci_level'))}%" if ex.get("ci_level") is not None else CI_LEVEL_WORDS
    head = ["## Share of the gap", ""]
    terms = (f"gauge ① at its fit-chosen global τ {fmt(doc.get('tau_global_gauge1'))} asks "
             f"{fmt(d.get('ask_gauge1_global_tau'))}, at its fit-chosen per-class τ "
             f"{fmt(d.get('ask_gauge1_per_class_tau'))}; gauge ③ at its per-class τ asks "
             f"{fmt(d.get('ask_gauge3_per_class_tau'))}")
    if doc.get("defined"):
        line = (f"The analogue of the per-category threshold rung, on the {fmt(ex.get('n_exam'))}-item exam with the ask "
                f"rate at the selective-accuracy target as the metric: {terms}. Per-class thresholds on the zero-shot "
                f"read close a share **{fmt(d.get('share'))}** of the gap between gauge ① at its global τ and gauge ③ "
                f"(numerator {fmt(d.get('numerator'))}, denominator {fmt(d.get('denominator'))} points; {level} paired "
                f"bootstrap CIs, {fmt(ex.get('n_boot'))} resamples).")
    else:
        line = (f"The analogue of the per-category threshold rung, on the {fmt(ex.get('n_exam'))}-item exam: {terms}; "
                f"share: **{fmt(d.get('share'))}** (denominator {fmt(d.get('denominator'))} points, {level} paired "
                f"bootstrap CI).")
    return head + [line]


GAUGEJ_SCORE = "gaugeJ_score.json"
GAUGEJ_NAME = "gauge J JSON emission ‡"


def load_gauge_j() -> dict | None:
    """results/gaugeJ_score.json once it carries an exam block (PREREG Amendment 2), else None."""
    path = RESULTS_DIR / GAUGEJ_SCORE
    doc = load_json_dict(path) if path.is_file() else None
    return doc if isinstance(doc, dict) and isinstance(doc.get("exam"), dict) else None


def gauge_j_table_row(doc: dict) -> str:
    """Gauge J's row in the results table, appended after the Gate 3 / 4 rows and outside their † marks:
    accuracy = J-trust, ask rate and selective accuracy = J-gated; ECE and AUROC are not registered for J."""
    d = doc.get("display") or {}
    cells = [GAUGEJ_NAME, fmt(dig(doc, "exam", "n_exam")), fmt(d.get("trust_accuracy")), DASH,
             fmt(d.get("gated_ask_rate")), fmt(d.get("gated_selective_accuracy")), DASH]
    return "| " + " | ".join(cells) + " |"


def gauge_j_footnote(doc: dict) -> str:
    ex = doc["exam"]
    return (f"‡ Gauge J (pre-registered in PREREG.md, {code(fmt(doc.get('prereg_section')))}): accuracy is J-trust (the "
            "emitted decision taken as given, a parse failure counted as wrong); ask rate and selective accuracy are "
            "J-gated (per-class thresholds on the emitted confidence, a parse failure counted as an ask). Its CIs use "
            f"{fmt(ex.get('n_boot'))} resamples paired with gauge ①, so it is left out of the † marks; parse failures, "
            "the paired difference and latency are in the Gauge J section.")


def gauge_j_section() -> list[str]:
    """Amendment 2: J-trust, J-gated, parse failures, the paired ask-rate difference against gauge ① and the latency
    line — every number a display string or value of results/gaugeJ_score.json."""
    doc = load_gauge_j()
    if doc is None:
        return []
    d, ex, c, th = doc.get("display") or {}, doc["exam"], doc.get("counts") or {}, doc.get("thresholds") or {}
    lat = doc.get("latency") or {}
    level = f"{fmt(ex.get('ci_level'))}%" if ex.get("ci_level") is not None else CI_LEVEL_WORDS
    reach = ("reaches the target on the fit split" if th.get("target_reachable_on_fit")
             else "target not reachable on the fit split: the τ with the best fit selective accuracy, all classes")
    out = ["## Gauge J — JSON emission", "",
           "The common practice: ask the model to emit a JSON field and trust it. Gauge J asks the engine of gauge ① — "
           "the same tool list and request, without the lettered options — to reply with only "
           '`{"decision": "none" | "one" | "several", "confidence": …}`; greedy decoding, at most '
           f"{fmt(doc.get('max_new_tokens'))} new tokens, one generation per item, no retries, parsed from the first "
           f"JSON object. Pre-registered in PREREG.md ({code(fmt(doc.get('prereg_section')))}) before gauge J read any "
           "set-A item; the exam was read once.", "",
           f"| gauge J row | n | accuracy [CI] | ask rate @ SA {fmt(ex.get('sa_target'))} [CI] | "
           "selective accuracy achieved [CI] | parse failures [CI] |",
           "|---|---|---|---|---|---|",
           f"| J-trust: take the field, never ask | {fmt(ex.get('n_exam'))} | {fmt(d.get('trust_accuracy'))} | never asks | "
           f"{DASH} | {fmt(d.get('parse_failure_rate'))} |",
           f"| J-gated: per-class τ on the emitted confidence | {fmt(ex.get('n_exam'))} | {DASH} | "
           f"{fmt(d.get('gated_ask_rate'))} | {fmt(d.get('gated_selective_accuracy'))} | {fmt(d.get('parse_failure_rate'))} |",
           "",
           f"Thresholds τ (none, one, several) = {fmt(d.get('taus'))}, fitted on the {fmt(th.get('n_fit'))} fit items "
           f"with gauge ①'s procedure ({reach}); on the fit split J-gated asks {fmt(d.get('fit_ask_rate'))} at selective "
           f"accuracy {fmt(d.get('fit_selective_accuracy'))}. Parse failures on the exam: {fmt(c.get('n_parse_failure'))} "
           f"of {fmt(c.get('n'))} ({fmt(c.get('n_finish_length'))} cut off at the token cap). Of the parsed replies, "
           f"{fmt(c.get('n_confidence_1'))} report confidence exactly one.",
           "",
           f"Paired with gauge ① on the same resamples: ask rate J-gated − gauge ① (per-class τ, "
           f"{fmt(d.get('gauge1_ask_rate_value'))}) = **{fmt(d.get('ask_diff_points'))}** points — "
           f"{fmt(d.get('paired_verdict'))}."
           + ("" if th.get("target_reachable_on_fit") else
              f" Read it with the selective-accuracy column: J-gated does not reach the {fmt(ex.get('sa_target'))} target, "
              "so a lower ask rate than gauge ① is not a gain at equal selective accuracy."),
           "",
           f"Latency per decision on the same {fmt(lat.get('n_items'))} {fmt(lat.get('split'))} items, one session: "
           f"gauge J {fmt(d.get('latency_gaugeJ'))}; gauge ① (three-rotation read) {fmt(d.get('latency_gauge1'))}.",
           "",
           f"{level} percentile bootstrap CIs, {fmt(ex.get('n_boot'))} resamples, seed {fmt(ex.get('seed'))}, over the "
           f"{fmt(ex.get('n_exam'))} exam items in file order; thresholds fitted on the fit split only."]
    return out


LABELS_NEEDED_REL = "results/labels-needed.png"


def labels_needed_section() -> list[str]:
    """Task C: per-n table, the pre-registered smallest-n line with its caveat, and the figure — every number
    from results/labels-needed.json (its display strings and lists)."""
    path = RESULTS_DIR / "labels-needed.json"
    doc = load_json_dict(path) if path.is_file() else None
    if not isinstance(doc, dict) or not isinstance(doc.get("exam"), dict) or not doc.get("summary"):
        return []
    ex = doc["exam"]
    level = f"{fmt(ex.get('ci_level'))}%" if ex.get("ci_level") is not None else CI_LEVEL_WORDS
    ref = doc.get("gauge1_reference") or {}
    out = ["## Labels needed (gauge ③ head)", "",
           f"The gauge ③ head retrained on n fit labels (equal per class), {fmt(len(doc['variants']))} variants in all; "
           f"each variant's T and per-class thresholds are fitted on its own out-of-fold fit predictions, then the "
           f"{fmt(ex.get('n_exam'))}-item exam is scored once per variant. Mean over draws (min–max) and the paired "
           f"{level} bootstrap CI of the draw mean ({fmt(ex.get('n_boot'))} exam resamples, seed {fmt(ex.get('seed'))}; "
           "the CI does not include draw-to-draw variation, the min–max does).", "",
           "| fit labels n | draws | exam accuracy | ask rate @ SA "
           f"{fmt(ex.get('sa_target'))} | selective accuracy achieved | draws meeting the SA target | "
           "within noise of gauge ① or better |",
           "|---|---|---|---|---|---|---|"]
    for row in doc["summary"]:
        d = row.get("display") or {}
        out.append("| " + " | ".join([fmt(row.get("n")), fmt(row.get("draws")), fmt(d.get("accuracy")),
                                      fmt(d.get("ask_rate")), fmt(d.get("selective_accuracy")),
                                      fmt(d.get("draws_meeting_target")), fmt(d.get("within_noise_or_better"))]) + " |")
    out.append("")
    below = doc.get("n_with_mean_sa_below_target") or []
    out.append(
        f"Smallest n whose mean ask rate is within noise of gauge ①'s or better (pre-registered rule; gauge ① "
        f"{fmt(dig(ref, 'display', 'ask_rate'))}): **{fmt(doc.get('smallest_n_display'))}**."
        + (f" Read it with the selective-accuracy column: at n = {', '.join(fmt(n) for n in below)} the draw-mean "
           f"selective accuracy achieved on the exam is below the {fmt(ex.get('sa_target'))} target (gauge ①: "
           f"{fmt(dig(ref, 'display', 'selective_accuracy'))}), so thresholds fitted on that few out-of-fold "
           "predictions under-ask — a lower ask rate there is not an improvement at equal selective accuracy."
           if below else "")
    )
    if (ROOT / LABELS_NEEDED_REL).exists():
        out += ["", f"![labels needed by the gauge ③ head]({LABELS_NEEDED_REL})"]
    return out


def engines_in_results() -> set[str]:
    """Non-constant engines named by results gauge files — the engines the README reports on (the same set
    selftest check d requires a card for). A card whose engine has no result yet is not printed."""
    names: set[str] = set()
    if RESULTS_DIR.exists():
        for path in sorted(RESULTS_DIR.glob("*.json")):
            if path.name.endswith(".calib.json"):
                continue
            data = load_json(path)
            if isinstance(data, dict) and "gauge" in data and isinstance(data.get("items"), list):
                eng = data.get("engine")
                if isinstance(eng, str) and eng and eng != "constant":
                    names.add(eng)
    return names


def engines_section() -> list[str]:
    out = ["## Engines and licenses", ""]
    cards = []
    if CARDS_DIR.exists():
        used = engines_in_results()
        cards = [p for p in sorted(CARDS_DIR.glob("*.md")) if p.name != "README.md" and p.stem in used]
    if not cards:
        out.append("No engine card yet.")
    for card in cards:
        line = first_license_line(card)
        if line is None:
            warn(f"{card.name}: no line starting with 'license:'")
            line = "(no license line in card)"
        out.append(f"- {card.stem}: {line}")
    return out


def _fulfilled(result_file: str | None) -> bool:
    if result_file is None:
        return False
    data = load_json(RESULTS_DIR / result_file) if (RESULTS_DIR / result_file).is_file() else None
    return isinstance(data, dict) and isinstance(data.get("exam"), dict)


def promised_section() -> list[str]:
    left = [name for name, result_file in PROMISED if not _fulfilled(result_file)]
    return ["## Promised, not claimed", "", "promised, not claimed: " + (", ".join(left) if left else DASH)]


def build(manifest: dict, rows: list[dict]) -> str:
    lines: list[str] = []
    lines += intro_section()
    lines += [""] + install_section()
    lines += [""] + seta_section(manifest)
    lines += [""] + results_section(rows)
    for section in (like_for_like_section(), labels_needed_section(), share_of_gap_section(), gauge_j_section()):
        if section:
            lines += [""] + section
    lines += [""] + engines_section()
    lines += [""] + promised_section()
    lines += ["", FOOTER]
    return "\n".join(lines) + "\n"


# ----------------------------------------------------------------------------- main

def main(argv=None) -> int:
    ap = argparse.ArgumentParser(
        prog="nikasha.readme",
        description="Write README.md from data/seta/manifest.json, results/*.json and cards/. "
                    "Every number is copied verbatim from a JSON value.")
    ap.add_argument("--stdout", action="store_true",
                    help="print the README to stdout instead of writing README.md")
    args = ap.parse_args(argv)

    if not MANIFEST_PATH.exists():
        raise SystemExit(f"readme: manifest not found: {MANIFEST_PATH} — build set A first")
    manifest = read_json(MANIFEST_PATH)
    if not isinstance(manifest, dict):
        raise SystemExit(f"readme: manifest is not a JSON object: {MANIFEST_PATH}")

    rows = load_rows()
    text = build(manifest, rows)
    gauges = ", ".join(r["id"] for r in rows) or "none"
    if args.stdout:
        sys.stdout.write(text)
        print(f"readme: {len(rows)} result rows ({gauges}); nothing written", file=sys.stderr)
    else:
        README_PATH.write_text(text, encoding="utf-8")
        print(f"{README_PATH}: {len(rows)} result rows written ({gauges})")
    return 0


if __name__ == "__main__":
    sys.exit(main())
