"""selftest — repo consistency checks. Prints one line per check and ends with SELFTEST GREEN (exit 0)
or SELFTEST RED (exit 1). GREEN means every line is PASS, SKIP or WARN; a single FAIL makes it RED.

Checks:
  a  fit ids and exam ids are disjoint and both files are non-empty. Only the "id" field of each row is
     read; no request or function text is kept or printed (brief rule 4 / Task 6).
  b  every item of every results gauge file (top-level results/*.json carrying "gauge" and a list "items")
     has probs_raw of length 3, entries in [0, 1], sum within 1e-6 of 1 (the gauge contract). A gauge
     file whose item count differs from n_fit + n_exam, and any interrupted-run checkpoint
     (results/*.partial.json or "partial": true), is a FAIL: a truncated gauge file is not a gauge.
  c  every number printed in README.md occurs in results/*.json (including .calib.json) or
     data/seta/manifest.json, compared through decimal.Decimal (rule 10: no number by hand). The
     allowed set is built exactly as specified: JSON numbers (repr and str) and number tokens inside
     JSON string VALUES; dict keys and the absolute value of negative numbers are not consulted.
  d  one license line per distinct non-"constant" engine named in results gauge files:
     cards/<engine>.md exists and has a line starting with "license:".
  e  sha256(exam.jsonl) and sha256(fit.jsonl) equal the manifest's.
  f  every exam.scored_at is preceded by a commit of PREREG.md (rule 9): the version in force at scoring
     time is the latest PREREG.md commit before it, and an exam block that records `prereg_commit` must
     name exactly that commit's date. PREREG.md is amended, never rewritten: every later committed version
     (and the working tree) starts with the full text in force at the first exam block. SKIP while no
     exam block exists.
  g  README.md exists, carries the readme.py marker, and is at least as new as the JSON it depends on
     (WARN, not FAIL, when older). results/*.partial.json and results/timing-*.json are not README
     inputs and are left out of that comparison.
  h  every results/<gauge>.calib.json carries fit_fingerprint and it equals nikasha.fit_fingerprint of
     results/<gauge>.json (sha256 over sorted fit ids + logits_mean): the calibration belongs to this run.
     An exam block that records fit_fingerprint must match it too; score.py's guard refuses a tampered run.
  i  PREREG Amendment 1 (Gate 4): its commit predates every new exam block, each block records it, the Gate 3
     blocks predate it, and it is on HEAD (WARN while not yet on origin/main, e.g. before a force-push).
  j  gauge ③'s fit-split logits are flagged oof: true and reproduce as out-of-fold values by refitting per fold.
  k  no key material anywhere in the repo: the key prefix is in no file (.git included) and in no commit.

Run from the repo root:  ~/venvs/nikasha/bin/python -m nikasha.selftest
This module never imports an engine and never prints the text of any set-A item.
"""
from __future__ import annotations

import argparse
import json
import re
import subprocess
import sys
from datetime import datetime, timezone
from decimal import Decimal, InvalidOperation
from pathlib import Path

from nikasha import (
    CARDS_DIR,
    EXAM_PATH,
    FIT_PATH,
    MANIFEST_PATH,
    RESULTS_DIR,
    ROOT,
    fit_fingerprint,
    read_json,
    sha256_file,
)

PASS, FAIL, WARN, SKIP = "PASS", "FAIL", "WARN", "SKIP"

README_PATH = ROOT / "README.md"
PREREG_PATH = ROOT / "PREREG.md"
README_MARKER = "Generated by nikasha/readme.py"

# README number tokens: digits with optional thousands separators, decimal part, exponent and trailing %.
# The exponent part is needed because readme.py prints floats through json.dumps, which writes any
# |x| < 1e-4 as e.g. "3.0517578125e-05"; without it that token would split into "3.0517578125" and "05".
# The same regex scans JSON string values, so both sides of check c stay symmetric.
NUM_RE = re.compile(r"\d[\d,]*(?:\.\d+)?(?:[eE][-+]?\d+)?%?")
PROB_TOL = 1e-6
MAX_SHOWN = 5  # how many offending ids / items a single line names


# --------------------------------------------------------------------------- shared loading


def _load_json(path: Path):
    """Return (obj, None) on success or (None, reason) on failure; never raises."""
    try:
        return read_json(path), None
    except Exception as exc:  # noqa: BLE001 — any parse/IO error is a finding, not a crash
        return None, f"{type(exc).__name__}: {exc}"


class Repo:
    """Everything the checks share: top-level results/*.json (parsed once) and the manifest."""

    def __init__(self) -> None:
        if RESULTS_DIR.is_dir():
            # Non-recursive on purpose: sub-directories under results/ are not gauge outputs.
            self.results_files = sorted(p for p in RESULTS_DIR.glob("*.json") if p.is_file())
        else:
            self.results_files = []
        self.results: dict[Path, tuple] = {p: _load_json(p) for p in self.results_files}
        if MANIFEST_PATH.is_file():
            self.manifest, self.manifest_err = _load_json(MANIFEST_PATH)
        else:
            self.manifest, self.manifest_err = None, "data/seta/manifest.json missing"

    def gauge_files(self) -> list[tuple[Path, dict]]:
        out = []
        for p, (obj, err) in self.results.items():
            if err or not isinstance(obj, dict):
                continue
            if "gauge" in obj and isinstance(obj.get("items"), list):
                out.append((p, obj))
        return out


def _read_ids(path: Path) -> tuple[list[str], list[int]]:
    """Return (ids, bad_line_numbers). Only the "id" of each row is kept; the row itself is dropped."""
    ids: list[str] = []
    bad: list[int] = []
    with open(path, encoding="utf-8") as f:
        for n, line in enumerate(f, 1):
            line = line.strip()
            if not line:
                continue
            try:
                row = json.loads(line)
            except json.JSONDecodeError:
                bad.append(n)
                continue
            item_id = row.get("id") if isinstance(row, dict) else None
            del row
            if item_id is None:
                bad.append(n)
            else:
                ids.append(str(item_id))
    return ids, bad


# --------------------------------------------------------------------------- number normalisation


def _canon(token: str) -> str | None:
    """Canonical numeric form of a token: strip ',' and '%', parse as Decimal, drop trailing zeros.

    "0.70" -> "0.7", "1,000" -> "1000", "68.0" -> "68", "07" -> "7", "3.05e-05" -> "0.0000305".
    None when not a finite number.
    """
    s = token.replace(",", "").replace("%", "").strip()
    if not s:
        return None
    try:
        d = Decimal(s)
        if not d.is_finite():
            return None
        if d == 0:
            return "0"
        return format(d.normalize(), "f")
    except ArithmeticError:  # InvalidOperation; Overflow from hex digests such as "...6e5967613..." in a sha256
        return None


def _collect_text_numbers(text: str, out: set[str]) -> None:
    for tok in NUM_RE.findall(text):
        c = _canon(tok)
        if c is not None:
            out.add(c)


def _collect_json_numbers(obj, out: set[str]) -> None:
    """Every JSON number (shortest repr and str) and every number token inside JSON string values.

    Exactly the spec's construction: dict keys are not scanned (otherwise "sha256" would admit 256 and
    "BFCL_v3_*" would admit 3) and a negative number admits only its signed form (otherwise the
    baselines' -40.0 logits would admit a hand-typed 40). README tokens never carry a sign, so a
    negative JSON number can never vouch for a README number; readme.py prints none."""
    if obj is None or isinstance(obj, bool):
        return
    if isinstance(obj, (int, float)):
        for s in (repr(obj), str(obj)):
            c = _canon(s)
            if c is not None:
                out.add(c)
    elif isinstance(obj, str):
        _collect_text_numbers(obj, out)
    elif isinstance(obj, dict):
        for v in obj.values():
            _collect_json_numbers(v, out)
    elif isinstance(obj, (list, tuple)):
        for v in obj:
            _collect_json_numbers(v, out)


# --------------------------------------------------------------------------- checks
# Each check returns a list of (status, letter, message) tuples.


def check_a(repo: Repo) -> list[tuple[str, str, str]]:
    """fit_ids ∩ exam_ids = ∅ and both files non-empty (ids only)."""
    for name, path in (("fit.jsonl", FIT_PATH), ("exam.jsonl", EXAM_PATH)):
        if not path.is_file():
            return [(FAIL, "a", f"{name} missing at {path.relative_to(ROOT)}")]
    fit_ids, fit_bad = _read_ids(FIT_PATH)
    exam_ids, exam_bad = _read_ids(EXAM_PATH)
    problems: list[str] = []
    if fit_bad:
        problems.append(f"fit.jsonl has {len(fit_bad)} malformed/id-less line(s), first at line {fit_bad[0]}")
    if exam_bad:
        problems.append(f"exam.jsonl has {len(exam_bad)} malformed/id-less line(s), first at line {exam_bad[0]}")
    if not fit_ids:
        problems.append("fit.jsonl is empty")
    if not exam_ids:
        problems.append("exam.jsonl is empty")
    dup_fit = len(fit_ids) - len(set(fit_ids))
    dup_exam = len(exam_ids) - len(set(exam_ids))
    if dup_fit:
        problems.append(f"fit.jsonl has {dup_fit} duplicate id(s)")
    if dup_exam:
        problems.append(f"exam.jsonl has {dup_exam} duplicate id(s)")
    overlap = sorted(set(fit_ids) & set(exam_ids))
    if overlap:
        shown = ", ".join(overlap[:MAX_SHOWN]) + (" ..." if len(overlap) > MAX_SHOWN else "")
        problems.append(f"{len(overlap)} id(s) appear in both splits: {shown}")
    tail = f"n_fit={len(fit_ids)}, n_exam={len(exam_ids)}"
    if problems:
        return [(FAIL, "a", "; ".join(problems) + f" ({tail})")]
    return [(PASS, "a", f"fit and exam ids disjoint and non-empty ({tail}, overlap=0)")]


def _probs_problem(p) -> str | None:
    if not isinstance(p, (list, tuple)):
        return "probs_raw missing or not a list"
    if len(p) != 3:
        return f"probs_raw has length {len(p)}, expected 3"
    vals: list[float] = []
    for x in p:
        if isinstance(x, bool) or not isinstance(x, (int, float)):
            return "probs_raw has a non-numeric entry"
        x = float(x)
        if x != x or x in (float("inf"), float("-inf")):
            return "probs_raw has a non-finite entry"
        vals.append(x)
    if any(x < 0.0 or x > 1.0 for x in vals):
        return f"probs_raw entry outside [0,1]: {vals}"
    s = sum(vals)
    if abs(s - 1.0) > PROB_TOL:
        return f"probs_raw sums to {s!r} (|sum-1| = {abs(s - 1.0):.3g} > {PROB_TOL:g})"
    return None


def check_b(repo: Repo) -> list[tuple[str, str, str]]:
    """Every probability vector in every results file with items obeys the gauge contract."""
    out: list[tuple[str, str, str]] = []
    n_gauge = 0
    for p, (obj, err) in repo.results.items():
        if err:
            out.append((FAIL, "b", f"{p.name}: unreadable JSON ({err})"))
            continue
        if not isinstance(obj, dict):
            continue
        if p.name.endswith(".partial.json") or obj.get("partial") is True:
            # gauge_logit.py checkpoints results/gauge1-logit.partial.json every few items and unlinks
            # it only on a successful finish; a leftover one is a truncated gauge file, never a gauge.
            n_items = len(obj["items"]) if isinstance(obj.get("items"), list) else 0
            out.append((FAIL, "b", f"{p.name}: interrupted gauge-run checkpoint ({n_items} items, "
                        f"n_done={obj.get('n_done')}, n_total={obj.get('n_total')}) -- "
                        "finish the run or remove the file"))
            continue
        if not isinstance(obj.get("items"), list):
            continue
        items = obj["items"]
        is_gauge = "gauge" in obj
        if is_gauge:
            n_gauge += 1
            if not items:
                out.append((FAIL, "b", f"{p.name}: gauge file with an empty items list"))
                continue
            n_fit, n_exam = obj.get("n_fit"), obj.get("n_exam")
            # an external gauge lists the items it could not get an answer for in `failed` (never dropped silently)
            n_failed = len(obj["failed"]) if obj.get("external") is True and isinstance(obj.get("failed"), list) else 0
            if (all(isinstance(x, int) and not isinstance(x, bool) for x in (n_fit, n_exam))
                    and len(items) + n_failed != n_fit + n_exam):
                out.append((FAIL, "b", f"{p.name}: {len(items)} items + {n_failed} failed but n_fit + n_exam = "
                            f"{n_fit} + {n_exam} = {n_fit + n_exam} (truncated or padded gauge file)"))
        n_checked = 0
        failures: list[str] = []
        for i, item in enumerate(items):
            is_dict = isinstance(item, dict)
            if not is_gauge and not (is_dict and "probs_raw" in item):
                continue  # non-gauge file (e.g. canary.json): only validate vectors that exist
            n_checked += 1
            problem = _probs_problem(item.get("probs_raw") if is_dict else None)
            if problem:
                item_id = item.get("id", "?") if is_dict else "?"
                failures.append(f"item[{i}] id={item_id}: {problem}")
        if not is_gauge and n_checked == 0:
            out.append((SKIP, "b", f"{p.name}: {len(items)} items carry no probs_raw (not a gauge file)"))
            continue
        if failures:
            shown = "; ".join(failures[:MAX_SHOWN])
            if len(failures) > MAX_SHOWN:
                shown += f"; ... {len(failures) - MAX_SHOWN} more"
            out.append((FAIL, "b", f"{p.name}: {len(failures)} of {n_checked} probs_raw invalid -- {shown}"))
        else:
            out.append((PASS, "b", f"{p.name}: {n_checked} probs_raw vectors valid (len 3, in [0,1], sum within 1e-6)"))
    if n_gauge == 0:
        out.append((SKIP, "b", 'no results gauge file (results/*.json with "gauge" and "items") found'))
    return out


def check_c(repo: Repo) -> list[tuple[str, str, str]]:
    """Every number in README.md occurs in results/*.json or manifest.json (Decimal-normalised)."""
    if not README_PATH.is_file():
        return [(FAIL, "c", "README.md missing -- cannot check its numbers")]
    text = README_PATH.read_text(encoding="utf-8", errors="replace")
    readme: dict[str, str] = {}  # canonical -> first raw token as printed
    unreadable: list[str] = []
    for tok in NUM_RE.findall(text):
        c = _canon(tok)
        if c is None:
            unreadable.append(tok)
        elif c not in readme:
            readme[c] = tok
    if unreadable:
        return [(FAIL, "c", f"README.md prints {len(unreadable)} number-like token(s) that do not parse as finite "
                            f"numbers: {', '.join(unreadable[:MAX_SHOWN])}")]
    allowed: set[str] = set()
    n_sources = 0
    notes: list[str] = []
    for p, (obj, err) in repo.results.items():
        if err:
            notes.append(f"{p.name} unreadable")
            continue
        _collect_json_numbers(obj, allowed)
        n_sources += 1
    if repo.manifest is None:
        notes.append(f"manifest not used ({repo.manifest_err})")
    else:
        _collect_json_numbers(repo.manifest, allowed)
        n_sources += 1
    missing = sorted((c for c in readme if c not in allowed), key=Decimal)
    note_txt = f" [{'; '.join(notes)}]" if notes else ""
    if not readme:
        return [(PASS, "c", f"README.md prints no numbers; {n_sources} JSON source(s) scanned{note_txt}")]
    if missing:
        shown = []
        for c in missing:
            raw = readme[c]
            stripped = raw.replace(",", "").replace("%", "")
            shown.append(raw if stripped == c else f"{raw} (={c})")
        return [(FAIL, "c",
                 f"{len(missing)} of {len(readme)} distinct README number(s) occur in no JSON: "
                 f"{', '.join(shown)}{note_txt}")]
    return [(PASS, "c", f"all {len(readme)} distinct README numbers occur in {n_sources} JSON source(s){note_txt}")]


def check_d(repo: Repo) -> list[tuple[str, str, str]]:
    """cards/<engine>.md with a 'license:' line for every non-constant engine in results gauge files."""
    engines: set[str] = set()
    for _p, obj in repo.gauge_files():
        eng = obj.get("engine")
        if isinstance(eng, str) and eng and eng != "constant":
            engines.add(eng)
    if not engines:
        return [(SKIP, "d", "no non-constant engine named in any results gauge file")]
    out: list[tuple[str, str, str]] = []
    for eng in sorted(engines):
        if "/" in eng or eng in (".", "..") or eng != eng.strip():
            out.append((FAIL, "d", f"engine name {eng!r} is not a plain card name"))
            continue
        card = CARDS_DIR / f"{eng}.md"
        if not card.is_file():
            out.append((FAIL, "d", f"cards/{eng}.md missing (engine {eng})"))
            continue
        lines = card.read_text(encoding="utf-8", errors="replace").splitlines()
        n_lic = sum(1 for ln in lines if ln.lstrip().startswith("license:"))
        if n_lic == 0:
            out.append((FAIL, "d", f"cards/{eng}.md has no line starting with 'license:'"))
        elif n_lic > 1:
            out.append((WARN, "d", f"cards/{eng}.md has {n_lic} 'license:' lines; readme.py prints the first"))
        else:
            out.append((PASS, "d", f"cards/{eng}.md has one license line"))
    return out


def check_e(repo: Repo) -> list[tuple[str, str, str]]:
    """sha256 of exam.jsonl and fit.jsonl equal the manifest's."""
    out: list[tuple[str, str, str]] = []
    sha = repo.manifest.get("sha256") if isinstance(repo.manifest, dict) else None
    for name, path in (("exam.jsonl", EXAM_PATH), ("fit.jsonl", FIT_PATH)):
        if repo.manifest is None:
            out.append((FAIL, "e", f"{name}: manifest unavailable ({repo.manifest_err})"))
            continue
        expected = sha.get(name) if isinstance(sha, dict) else None
        if not isinstance(expected, str) or not expected:
            out.append((FAIL, "e", f"{name}: manifest has no sha256[{name!r}]"))
            continue
        if not path.is_file():
            out.append((FAIL, "e", f"{name}: file missing"))
            continue
        actual = sha256_file(path)
        if actual.lower() == expected.strip().lower():
            out.append((PASS, "e", f"{name} sha256 {actual[:12]}... equals manifest"))
        else:
            out.append((FAIL, "e", f"{name} sha256 {actual[:12]}... != manifest {expected[:12]}..."))
    return out


def _parse_iso(s: str) -> datetime:
    s = s.strip()
    if s[-1:] in ("Z", "z"):
        s = s[:-1] + "+00:00"
    dt = datetime.fromisoformat(s)
    if dt.tzinfo is None:
        dt = dt.replace(tzinfo=timezone.utc)
    return dt


def _git(*args: str) -> tuple[int, str, str]:
    try:
        r = subprocess.run(["git", *args], cwd=str(ROOT), capture_output=True, text=True,
                           timeout=60, check=False)
    except (OSError, subprocess.TimeoutExpired) as exc:
        return 127, "", f"{type(exc).__name__}: {exc}"
    return r.returncode, r.stdout.strip(), r.stderr.strip()


def prereg_history() -> tuple[list[tuple[str, datetime, str]], str | None]:
    """Commits that touched PREREG.md, oldest first: (sha, commit datetime, raw ISO date). (list, error)."""
    rc, out_txt, err_txt = _git("log", "--format=%H %cI", "--", "PREREG.md")
    if rc != 0:
        return [], f"git log for PREREG.md failed (rc={rc}): {err_txt or out_txt}"
    hist: list[tuple[str, datetime, str]] = []
    for line in out_txt.splitlines():
        parts = line.split()
        if len(parts) != 2:
            continue
        try:
            hist.append((parts[0], _parse_iso(parts[1]), parts[1]))
        except ValueError:
            return [], f"cannot parse PREREG.md commit date {parts[1]!r}"
    hist.sort(key=lambda t: t[1])
    return hist, None


def prereg_text_at(sha: str) -> str | None:
    rc, out_txt, _ = _git("show", f"{sha}:PREREG.md")
    return out_txt if rc == 0 else None


def in_force(hist: list[tuple[str, datetime, str]], when: datetime):
    """The PREREG.md commit in force at `when`: the latest one strictly before it (None if none)."""
    before = [h for h in hist if h[1] < when]
    return before[-1] if before else None


def exam_blocks(repo: Repo) -> list[tuple[str, dict]]:
    """(file name, exam block) for every results file carrying a top-level `exam` dict."""
    out = []
    for p, (obj, err) in repo.results.items():
        if err or not isinstance(obj, dict):
            continue
        exam = obj.get("exam")
        if isinstance(exam, dict):
            out.append((p.name, exam))
    return out


def check_f(repo: Repo) -> list[tuple[str, str, str]]:
    """Every exam.scored_at is preceded by a PREREG.md commit (the one in force, which a recorded
    prereg_commit must name); PREREG.md only grows by appending after the first exam block."""
    scored = [(name, exam.get("scored_at"), exam.get("prereg_commit")) for name, exam in exam_blocks(repo)]
    if not scored:
        return [(SKIP, "f", "no exam block in any results file yet; PREREG date check deferred")]
    if not PREREG_PATH.is_file():
        return [(FAIL, "f", "PREREG.md missing")]
    hist, err = prereg_history()
    if err:
        return [(FAIL, "f", err)]
    if not hist:
        return [(FAIL, "f", "PREREG.md has no commit in git history (rule 9: commit and push before the first exam read)")]
    bad: list[str] = []
    parsed: list[tuple[str, datetime, str, tuple]] = []
    for name, raw, recorded in scored:
        if not isinstance(raw, str) or not raw.strip():
            bad.append(f"{name}: exam.scored_at missing")
            continue
        try:
            dt = _parse_iso(raw)
        except ValueError:
            bad.append(f"{name}: unparsable exam.scored_at {raw!r}")
            continue
        force = in_force(hist, dt)
        if force is None:
            bad.append(f"{name}: scored_at {raw} precedes every PREREG.md commit")
            continue
        if isinstance(recorded, str) and recorded.strip():
            try:
                if _parse_iso(recorded) != force[1]:
                    bad.append(f"{name}: records prereg_commit {recorded} but the PREREG.md commit in force at "
                               f"{raw} is {force[2]} ({force[0][:7]})")
            except ValueError:
                bad.append(f"{name}: unparsable prereg_commit {recorded!r}")
        parsed.append((name, dt, raw, force))
    results: list[tuple[str, str, str]] = []
    if bad:
        results.append((FAIL, "f", "every exam block must be preceded by the PREREG.md commit it records: "
                        + "; ".join(bad)))
        return results
    earliest = min(parsed, key=lambda t: t[1])
    versions = sorted({t[3][0][:7] + " " + t[3][2] for t in parsed})
    results.append((PASS, "f", f"all {len(parsed)} exam.scored_at are preceded by the PREREG.md commit in force "
                    f"(versions in force: {', '.join(versions)}; earliest block {earliest[2]} in {earliest[0]})"))

    # amend, never rewrite: every PREREG.md version after the first exam block extends the text in force then
    base_sha, base_dt, base_raw = earliest[3]
    base_text = prereg_text_at(base_sha)
    if base_text is None:
        results.append((FAIL, "f", f"cannot read PREREG.md at {base_sha[:7]}"))
        return results
    later = [h for h in hist if h[1] > base_dt]
    rewritten = []
    for sha, _dt, raw in later:
        text = prereg_text_at(sha)
        if text is None or not text.startswith(base_text):
            rewritten.append(f"{sha[:7]} ({raw})")
    work = PREREG_PATH.read_text(encoding="utf-8")
    if not work.rstrip("\n").startswith(base_text.rstrip("\n")):
        rewritten.append("working tree")
    if rewritten:
        results.append((FAIL, "f", f"PREREG.md text in force at the first exam block ({base_sha[:7]}) was changed, "
                        f"not appended to, in: {', '.join(rewritten)}"))
    else:
        results.append((PASS, "f", f"PREREG.md is append-only since {base_sha[:7]} ({len(later)} later commit(s) "
                        f"and the working tree extend it)"))
    rc2, dirty, _ = _git("status", "--porcelain", "--", "PREREG.md")
    if rc2 == 0 and dirty:
        results.append((WARN, "f", "PREREG.md has uncommitted changes in the working tree; "
                        "the committed version is the pre-registration"))
    return results


def check_g(repo: Repo) -> list[tuple[str, str, str]]:
    """README.md exists, is generated by readme.py, and is not older than its JSON inputs (WARN)."""
    if not README_PATH.is_file():
        return [(FAIL, "g", "README.md missing")]
    text = README_PATH.read_text(encoding="utf-8", errors="replace")
    out: list[tuple[str, str, str]] = []
    if README_MARKER in text:
        out.append((PASS, "g", f"README.md carries the marker {README_MARKER!r}"))
    else:
        out.append((FAIL, "g", f"README.md lacks the marker {README_MARKER!r} (rule 10: README is written by readme.py)"))
    readme_m = README_PATH.stat().st_mtime
    # Inputs readme.py reads: gauge files, their .calib.json, canary.json, ku2-hidden.json, manifest.
    # Not inputs: an interrupted-run checkpoint (check b already FAILs it) and the KU4 timing probe.
    deps = [p for p in repo.results_files
            if not p.name.endswith(".partial.json") and not p.name.startswith("timing-")]
    if MANIFEST_PATH.is_file():
        deps.append(MANIFEST_PATH)
    newer = [p.name for p in deps if p.stat().st_mtime > readme_m]
    if newer:
        out.append((WARN, "g", f"README.md is older than {len(newer)} of its {len(deps)} JSON input(s): "
                    f"{', '.join(newer)} -- re-run readme.py"))
    else:
        out.append((PASS, "g", f"README.md mtime is >= all {len(deps)} JSON input(s)"))
    return out


def check_h(repo: Repo) -> list[tuple[str, str, str]]:
    """Each .calib.json is bound to its gauge run by fit_fingerprint (and so is any exam block recording one)."""
    out: list[tuple[str, str, str]] = []
    for p, obj in repo.gauge_files():
        calib_path = p.with_name(p.stem + ".calib.json")
        if not calib_path.is_file():
            if isinstance(obj.get("exam"), dict):
                out.append((FAIL, "h", f"{p.name}: scored but has no {calib_path.name}"))
            continue
        calib, err = repo.results.get(calib_path, (None, "not loaded"))
        if err or not isinstance(calib, dict):
            out.append((FAIL, "h", f"{calib_path.name}: unreadable ({err})"))
            continue
        stored = (calib.get("fit_fingerprint") or {}).get("sha256")
        actual = fit_fingerprint(obj["items"])
        if not isinstance(stored, str) or not stored:
            out.append((FAIL, "h", f"{calib_path.name}: no fit_fingerprint (run calibrate.py --stamp)"))
            continue
        problems = []
        if stored != actual["sha256"]:
            problems.append(f"calib {stored[:12]}... != gauge file {actual['sha256'][:12]}...")
        exam_fp = (obj.get("exam") or {}).get("fit_fingerprint") if isinstance(obj.get("exam"), dict) else None
        if exam_fp is not None and exam_fp != actual["sha256"]:
            problems.append(f"exam block records {str(exam_fp)[:12]}...")
        if problems:
            out.append((FAIL, "h", f"{p.name}: fit fingerprint mismatch -- " + "; ".join(problems)))
        else:
            out.append((PASS, "h", f"{calib_path.name} fit_fingerprint {stored[:12]}... matches {p.name} "
                        f"(n_fit={actual['n_fit']})"))
    if not out:
        out.append((SKIP, "h", "no gauge file with a .calib.json yet"))
        return out
    out.append(_refusal_probe(repo))
    return out


def _refusal_probe(repo: Repo) -> tuple[str, str, str]:
    """Behavioural half of check h: score.py's fingerprint guard must refuse a gauge whose fit logits
    changed after calibration. One fit logit of a calibrated gauge is nudged IN MEMORY and handed to
    score._check_fingerprint (the guard phase 1 runs before the exam is opened); nothing is written and
    exam.jsonl is never touched."""
    import contextlib
    import copy
    import io

    from nikasha import score

    for p, obj in repo.gauge_files():
        calib_path = p.with_name(p.stem + ".calib.json")
        fit_idx = next((i for i, it in enumerate(obj["items"])
                        if isinstance(it, dict) and it.get("split") == "fit"), None)
        if not calib_path.is_file() or fit_idx is None:
            continue
        tampered = copy.deepcopy(obj)
        tampered["items"][fit_idx]["logits_mean"][0] = float(tampered["items"][fit_idx]["logits_mean"][0]) + 1e-3
        sink = io.StringIO()
        try:
            with contextlib.redirect_stderr(sink):
                score._check_fingerprint(obj["gauge"], tampered, calib_path)
        except SystemExit as exc:
            if exc.code != 0 and "fingerprint" in sink.getvalue():
                return (PASS, "h", f"score.py refuses a tampered {p.name} (one fit logit +1e-3, in memory): "
                                   f"exit {exc.code}")
            return (FAIL, "h", f"score.py exited {exc.code} on a tampered {p.name} without a fingerprint message")
        return (FAIL, "h", f"score.py accepted a tampered {p.name} (one fit logit +1e-3): stale calib not refused")
    return (SKIP, "h", "no calibrated gauge with fit items to probe the refusal")


AMENDMENT_HEADING = "## Amendment 1 (Gate 4)"
GATE3_FILES = {"baseline-uniform.json", "baseline-majority.json", "gauge1-logit.json"}


def check_i(repo: Repo) -> list[tuple[str, str, str]]:
    """Rule 12 (brief 10): the commit that introduced Amendment 1 predates every new (Gate 4) exam block, every
    block recording the amendment names that commit, the Gate 3 blocks predate it (never re-scored), and the
    commit is on HEAD (FAIL otherwise). Not yet on origin/main is a WARN, not a FAIL: after the Gate 5 history
    rewrite the new commits exist locally until the force-push, and chronology is decided by commit dates, which
    the rewrite keeps."""
    blocks = exam_blocks(repo)
    new = [(n, ex) for n, ex in blocks if n not in GATE3_FILES]
    old = [(n, ex) for n, ex in blocks if n in GATE3_FILES]
    if not new:
        return [(SKIP, "i", "no Gate 4 exam block yet")]
    rc, out_txt, err_txt = _git("log", "--format=%H %cI", "-S", AMENDMENT_HEADING, "--", "PREREG.md")
    lines = [ln.split() for ln in out_txt.splitlines() if ln.strip()] if rc == 0 else []
    if not lines:
        return [(FAIL, "i", f"no commit introduces {AMENDMENT_HEADING!r} in PREREG.md ({err_txt or 'git log -S empty'})")]
    sha, raw = lines[-1][0], lines[-1][1]
    when = _parse_iso(raw)
    problems = []
    for name, ex in new:
        try:
            if not _parse_iso(str(ex.get("scored_at"))) > when:
                problems.append(f"{name}: scored_at {ex.get('scored_at')} does not follow the amendment")
        except ValueError:
            problems.append(f"{name}: unparsable scored_at")
        rec = ex.get("prereg_section_commit")
        if rec is None or ex.get("prereg_section") != AMENDMENT_HEADING:
            problems.append(f"{name}: exam block does not record the amendment it was read under")
        elif _parse_iso(str(rec)) != when:
            problems.append(f"{name}: records amendment commit {rec}, not {raw}")
    for name, ex in old:
        if not _parse_iso(str(ex.get("scored_at"))) < when:
            problems.append(f"{name}: Gate 3 block scored at {ex.get('scored_at')}, after the amendment (re-scored?)")
    rc2, _, _ = _git("merge-base", "--is-ancestor", sha, "HEAD")
    if rc2 != 0:
        problems.append(f"amendment commit {sha[:7]} is not on HEAD")
    if problems:
        return [(FAIL, "i", "; ".join(problems))]
    summary = (f"Amendment 1 commit {sha[:7]} ({raw}) predates all {len(new)} Gate 4 exam blocks "
               f"({', '.join(sorted(n for n, _ in new))}), each records it; the {len(old)} Gate 3 blocks predate it")
    rc3, _, _ = _git("merge-base", "--is-ancestor", sha, "origin/main")
    if rc3 != 0:
        return [(WARN, "i", f"{summary}; on HEAD but not yet on origin/main (push pending)")]
    return [(PASS, "i", f"{summary}; on origin/main")]


def check_j(repo: Repo) -> list[tuple[str, str, str]]:
    """gauge ③: fit-split logits flagged oof: true — and genuinely out-of-fold: refitting the head per stored fold
    (chosen C, features from results/gauge3-features.npy) reproduces them, and they differ from in-sample values."""
    path = RESULTS_DIR / "gauge3-probe.json"
    obj, err = repo.results.get(path, (None, "absent"))
    if err or not isinstance(obj, dict):
        return [(SKIP, "j", "results/gauge3-probe.json absent")]
    fit = [it for it in obj["items"] if it.get("split") == "fit"]
    exam = [it for it in obj["items"] if it.get("split") == "exam"]
    flags_ok = (obj.get("oof") is True and fit and all(it.get("oof") is True for it in fit)
                and all(it.get("oof") is False for it in exam)
                and all(isinstance(it.get("fold"), int) for it in fit))
    if not flags_ok:
        return [(FAIL, "j", "gauge3-probe.json: fit logits are not all flagged oof: true with a fold "
                            "(top-level oof, per-item oof/fold, exam items oof: false)")]
    out = [(PASS, "j", f"gauge3-probe.json: top-level oof true; {len(fit)} fit items oof: true with folds "
                       f"{sorted({it['fold'] for it in fit})}; {len(exam)} exam items oof: false")]
    try:
        import numpy as np

        from nikasha import metrics
        from nikasha.gauge_probe import fit_head, load_features

        X, index = load_features(RESULTS_DIR / "gauge3-features.npy", RESULTS_DIR / "gauge3-features.index.json")
        row = {i: k for k, i in enumerate(index["ids"])}
        Xf = X[[row[it["id"]] for it in fit]]
        y = metrics.labels_to_idx([it["label"] for it in fit])
        folds = np.array([it["fold"] for it in fit])
        stored = np.array([it["logits_mean"] for it in fit], dtype=float)
        oof = np.empty_like(stored)
        for k in sorted(set(folds.tolist())):
            m, _, _ = fit_head(Xf[folds != k], y[folds != k], float(obj["C"]))
            oof[folds == k] = m.decision_function(Xf[folds == k])
        insample = fit_head(Xf, y, float(obj["C"]))[0].decision_function(Xf)
        d_oof = float(np.abs(oof - stored).max())
        d_in = float(np.abs(insample - stored).max())
        if d_oof <= 1e-6 < d_in:
            out.append((PASS, "j", f"refit per stored fold reproduces the fit logits (max |diff| {d_oof:.1e}); "
                                   f"in-sample logits differ by up to {d_in:.2f}: they are out-of-fold"))
        else:
            out.append((FAIL, "j", f"fit logits not reproduced as out-of-fold values (max |oof diff| {d_oof:.3g}, "
                                   f"max |in-sample diff| {d_in:.3g})"))
    except Exception as exc:  # noqa: BLE001
        out.append((FAIL, "j", f"out-of-fold reproduction failed: {type(exc).__name__}: {exc}"))
    return out


def check_k(repo: Repo) -> list[tuple[str, str, str]]:
    """No key material anywhere in the repo: the key prefix (assembled here, so this file never contains it)
    occurs in no file under the repo root (the .git directory included, like grep -r) and in no commit of any
    ref (git log --all -p, i.e. decompressed history)."""
    needle = "-".join(("sk", "or")).encode()  # joined at run time: "+" of constants is folded into the .pyc
    hits = []
    for p in sorted(ROOT.rglob("*")):
        if p.is_file() and not p.is_symlink():
            try:
                if needle in p.read_bytes():
                    hits.append(str(p.relative_to(ROOT)))
            except OSError:
                continue
    try:
        hist = subprocess.run(["git", "log", "--all", "-p", "--no-color", "--no-ext-diff"], cwd=str(ROOT),
                              capture_output=True, timeout=300, check=False).stdout
    except (OSError, subprocess.TimeoutExpired) as exc:
        return [(FAIL, "k", f"git history scan failed: {type(exc).__name__}")]
    n_hist = hist.count(needle)
    if hits or n_hist:
        return [(FAIL, "k", f"key prefix found in {len(hits)} file(s) {hits[:MAX_SHOWN]} and {n_hist} history line(s)")]
    return [(PASS, "k", f"no key material: key prefix absent from every file under the repo root (.git included) "
                        f"and from the full history ({len(hist) // 1024} KiB of git log --all -p)")]


CHECKS = (
    ("a", check_a),
    ("b", check_b),
    ("c", check_c),
    ("d", check_d),
    ("e", check_e),
    ("f", check_f),
    ("g", check_g),
    ("h", check_h),
    ("i", check_i),
    ("j", check_j),
    ("k", check_k),
)


# --------------------------------------------------------------------------- main


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(
        prog="nikasha.selftest",
        description="Repo consistency checks (a-k); prints SELFTEST GREEN and exits 0, or SELFTEST RED and exits 1.",
    )
    ap.add_argument("--strict", action="store_true", help="treat WARN lines as FAIL")
    args = ap.parse_args(argv)

    repo = Repo()
    lines: list[tuple[str, str, str]] = []
    for letter, fn in CHECKS:
        try:
            lines.extend(fn(repo))
        except Exception as exc:  # noqa: BLE001 — a crashing check is itself a FAIL, not an abort
            lines.append((FAIL, letter, f"check crashed: {type(exc).__name__}: {exc}"))

    for status, letter, msg in lines:
        print(f"{status} [{letter}] {msg}")

    counts = {s: sum(1 for st, _, _ in lines if st == s) for s in (PASS, FAIL, WARN, SKIP)}
    red = counts[FAIL] > 0 or (args.strict and counts[WARN] > 0)
    print(f"checks: {counts[PASS]} PASS, {counts[FAIL]} FAIL, {counts[WARN]} WARN, {counts[SKIP]} SKIP")
    print("SELFTEST RED" if red else "SELFTEST GREEN")
    return 1 if red else 0


if __name__ == "__main__":
    sys.exit(main())
